class LocalizerZH():

    # 保留
    switch_language: str = (
        "請選擇應用程式語言，新的語言設定將在下次啟動時生效 …"
        "\n"
        "Select application language, changes will take effect on restart …"
    )
    switch_language_toast: str = (
        "應用程式語言切換成功，請重新啟動應用程式以使變更生效 …"
        "\n"
        "Language switched successfully, please restart the application for changes to take effect …"
    )

    # 通用
    add: str = "新增"
    edit: str = "修改"
    none: str = "無"
    back: str = "返回"
    next: str = "下一個"
    stop: str = "停止"
    start: str = "開始"
    timer: str = "計時器"
    close: str = "關閉"
    alert: str = "提醒"
    warning: str = "警告"
    confirm: str = "確認"
    cancel: str = "取消"
    auto: str = "自動"
    wiki: str = "功能說明"
    open: str = "開啟"
    select: str = "選取"
    inject: str = "注入"
    filter: str = "篩選"
    search: str = "搜尋"
    generate: str = "產生"
    placeholder: str = "請輸入關鍵字 …"
    task_success: str = "任務執行成功 …"
    alert_no_data: str = "沒有有效資料 …"
    alert_reset_timer: str = "將重設計時器，是否確認 … ？"
    alert_reset_translation: str = "將重設尚未完成的翻譯任務，是否確認開始新的翻譯任務 … ？"

    # 主頁面
    app_close_message_box: str = "確定是否退出程式 … ？"
    app_new_version: str = "點擊下載更新版本！"
    app_new_version_toast: str = "已找到新版本，版本號為 {VERSION}，請點擊左下角按鈕下載更新 …"
    app_new_version_update: str = "正在下載 {PERCENT} …"
    app_new_version_failure: str = "新版本下載失敗 … "
    app_new_version_success: str = "新版本下載成功 … "
    app_new_version_downloaded: str = "點擊套用新版本！"
    app_new_version_waiting_restart: str = "更新完成，應用程式即將關閉 …"
    app_theme_btn: str = "變換自如"
    app_language_btn: str = "字字珠璣"
    app_settings_page: str = "應用程式設定"
    app_platform_page: str = "介面管理"
    app_project_page: str = "專案設定"
    app_translation_page: str = "開始翻譯"
    app_basic_settings_page: str = "基礎設定"
    app_expert_settings_page: str = "專家設定"
    app_glossary_page: str = "詞彙表"
    app_text_preserve_page: str = "文字保護"
    app_text_replacement_page: str = "文字取代"
    app_pre_translation_replacement_page: str = "譯前取代"
    app_post_translation_replacement_page: str = "譯後取代"
    app_custom_prompt_navigation_item: str = "自訂提示詞"
    app_custom_prompt_zh_page: str = "中文提示詞"
    app_custom_prompt_en_page: str = "英文提示詞"
    app_laboratory_page: str = "實驗室"
    app_treasure_chest_page: str = "百寶箱"

    # 路徑
    path_bilingual: str = "雙語對照"
    path_glossary_export: str = "匯出_詞彙表"
    path_text_preserve_export: str = "匯出_文字保護"
    path_pre_translation_replacement_export: str = "匯出_翻譯前取代"
    path_post_translation_replacement_export: str = "匯出_翻譯後取代"
    path_result_check_kana: str = "結果檢查_假名殘留.json"
    path_result_check_hangeul: str = "結果檢查_諺文殘留.json"
    path_result_check_text_preserve: str = "結果檢查_文字保護.json"
    path_result_check_similarity: str = "結果檢查_相似度較高.json"
    path_result_check_glossary: str = "結果檢查_詞彙表未生效.json"
    path_result_check_untranslated: str = "結果檢查_未翻譯的項目.json"
    path_result_check_retry_count_threshold: str = "結果檢查_重試次數達到門檻值.json"
    path_result_batch_correction: str = "批次修正.xlsx"
    path_result_name_field_extraction: str = "姓名字段擷取.xlsx"

    # 日誌
    log_proxy: str = "網路代理已啟用 …"
    log_expert_mode: str = "專家模式已啟用 …"
    log_api_test_fail: str = "介面測試失敗 … "
    log_task_fail: str = "翻譯任務失敗 …"
    log_read_file_fail: str = "檔案讀取失敗 …"
    log_write_file_fail: str = "檔案寫入失敗 …"
    log_read_cache_file_fail: str = "從檔案讀取快取資料失敗 …"
    log_write_cache_file_fail: str = "向檔案寫入快取資料失敗 …"
    log_load_llama_cpp_slots_num_fail: str = "無法取得 [green]llama.cpp[/] 的回應資料 …"
    log_crash: str = "出現嚴重錯誤，程式即將退出，錯誤資訊已儲存至日誌檔 …"
    translator_max_round: str = "最大回合數"
    translator_current_round: str = "目前回合數"
    translator_api_url: str = "介面網址"
    translator_name: str = "介面名稱"
    translator_model: str = "模型名稱"
    translator_begin: str = "即將開始執行翻譯任務，預計任務總數為 {TASKS}, 請注意保持網路通暢 …"
    translator_writing: str = "正在寫入翻譯資料，請稍候 …"
    translator_done: str = "所有文字均已翻譯，翻譯任務已結束 …"
    translator_fail: str = "已達最大翻譯回合數，仍有部分文字未翻譯，請檢查翻譯結果 …"
    translator_stop: str = "翻譯任務已停止 …"
    translator_write: str = "翻譯結果已儲存至 {PATH} 目錄 …"
    translator_generate_task: str = "產生翻譯任務"
    translator_rule_filter: str = "規則篩選已完成，共篩選 {COUNT} 個無需翻譯的項目 …"
    translator_mtool_filter: str = "MToolOptimizer 前置處理已完成，共篩選 {COUNT} 個包含重複子句的項目 …"
    translator_language_filter: str = "語言篩選已完成，共篩選 {COUNT} 個不包含目標語言的項目 …"
    translator_task_response_think: str = "模型思考內容：\n"
    translator_task_response_result: str = "模型回覆內容：\n"
    translator_response_check_fail: str = "翻譯文本未通過檢查，將在下一回合的翻譯中自動重試"
    translator_response_check_fail_all: str = "全部翻譯文本未通過檢查，將在下一回合的翻譯中自動重試"
    translator_response_check_fail_part: str = "部分翻譯文本未通過檢查，將在下一回合的翻譯中自動重試"
    translator_task_success: str = "任務耗時 {TIME} 秒，文字行數 {LINES} 行，輸入消耗 {PT} Tokens，輸出消耗 {CT} Tokens"
    translator_too_many_task: str = "即時任務數較多，暫時停止顯示詳細結果以提升效能 …"
    translator_no_items: str = "沒有找到需要翻譯的資料，請確認輸入檔案與專案設定是否正確 …"
    translator_running: str = "任務正在執行中，請稍後再試 …"
    file_checker_kana: str = "已完成假名殘留檢查，未發現異常項目 …"
    file_checker_kana_full: str = "已完成假名殘留檢查，發現 {COUNT} 個異常項目，佔比為 {PERCENT} %，結果已寫入 [green]{TARGET}[/] …"
    file_checker_hangeul: str = "已完成諺文殘留檢查，未發現異常項目 …"
    file_checker_hangeul_full: str = "已完成諺文殘留檢查，發現 {COUNT} 個異常項目，佔比為 {PERCENT} %，結果已寫入 [green]{TARGET}[/] …"
    file_checker_text_preserve: str = "已完成文字保護檢查，未發現異常項目 …"
    file_checker_text_preserve_full: str = "已完成文字保護檢查，發現 {COUNT} 個異常項目，佔比為 {PERCENT} %，結果已寫入 [green]{TARGET}[/] …"
    file_checker_text_preserve_alert_key: str = "____提醒____"
    file_checker_text_preserve_alert_value: str = "本檔案內列出的是文字保護 **可能** 未生效的項目，請結合上下文情境進行實際判斷！"
    file_checker_similarity: str = "已完成相似度異常檢查，未發現異常項目 …"
    file_checker_similarity_full: str = "已完成相似度異常檢查，發現 {COUNT} 個異常項目，佔比為 {PERCENT} %，結果已寫入 [green]{TARGET}[/] …"
    file_checker_similarity_alert_key: str = "____提醒____"
    file_checker_similarity_alert_value: str = "本檔案內列出的是 **可能** 存在相似度較高情況的項目，請結合上下文情境進行實際判斷！"
    file_checker_glossary: str = "已完成未生效詞彙檢查，未發現異常項目 …"
    file_checker_glossary_full: str = "已完成未生效詞彙檢查，發現 {COUNT} 個異常項目，佔比為 {PERCENT} %，結果已寫入 [green]{TARGET}[/] …"
    platofrm_tester_key: str = "正在測試金鑰"
    platofrm_tester_messages: str = "任務提示詞："
    platofrm_tester_response_think: str = "模型思考內容："
    platofrm_tester_response_result: str = "模型返回結果："
    platofrm_tester_result: str = "共測試 {COUNT} 個介面，成功 {SUCCESS} 個，失敗 {FAILURE} 個 …"
    platofrm_tester_running: str = "任務正在執行中，請稍後再試 …"
    response_checker_unknown: str = "未知"
    response_checker_fail_data: str = "資料結構錯誤"
    response_checker_fail_line_count: str = "行數不一致"
    response_checker_line_error_kana: str = "假名殘留"
    response_checker_line_error_hangeul: str = "諺文殘留"
    response_checker_line_error_fake_reply: str = "偽回覆殘留"
    response_checker_line_error_empty_line: str = "存在空行"
    response_checker_line_error_similarity: str = "較高相似度"
    response_checker_line_error_degradation: str = "發生退化現象"
    response_decoder_glossary_by_json: str = "詞彙資料 -> 反序列化，共 {COUNT} 筆"
    response_decoder_glossary_by_rule: str = "詞彙資料 -> 分割後規則解析，共 {COUNT} 筆"
    response_decoder_translation_by_json: str = "翻譯資料 -> 反序列化，共 {COUNT} 筆"
    response_decoder_translation_by_rule: str = "翻譯資料 -> 分割後規則解析，共 {COUNT} 筆"

    # 應用程式設定
    app_settings_page_expert_title: str = "專家模式"
    app_settings_page_expert_content: str = "啟用此功能後，將顯示更多日誌資訊並提供更多進階設定選項（將在應用程式重新啟動後生效）"
    app_settings_page_font_hinting_title: str = "字型最佳化"
    app_settings_page_font_hinting_content: str = "啟用此功能後，應用程式內 UI 字型的邊緣渲染將更加圓潤（將在應用程式重新啟動後生效）"
    app_settings_page_scale_factor_title: str = "全域縮放比例"
    app_settings_page_scale_factor_content: str = "啟用此功能後，應用程式介面將依照所選比例進行縮放（將在應用程式重新啟動後生效）"
    app_settings_page_proxy_url: str = "範例 - http://127.0.0.1:7890"
    app_settings_page_proxy_url_title: str = "網路代理"
    app_settings_page_proxy_url_content: str = "啟用此功能後，將使用設定的代理位址傳送網路請求（將在應用程式重新啟動後生效）"
    app_settings_page_close: str = "應用程式即將關閉，請確認 …"

    # 介面管理
    platform_page_api_test_result: str = "介面測試結果：成功 {SUCCESS} 個，失敗 {FAILURE} 個 …"
    platform_page_api_activate: str = "啟用介面"
    platform_page_api_edit: str = "編輯介面"
    platform_page_api_args: str = "編輯參數"
    platform_page_api_test: str = "測試介面"
    platform_page_api_delete: str = "刪除介面"
    platform_page_widget_add_title: str = "介面清單"
    platform_page_widget_add_content: str = "在此新增和管理任何相容 OpenAI、Anthropic 格式的 LLM 模型介面"

    # 介面編輯
    platform_edit_page_name: str = "請輸入介面名稱 …"
    platform_edit_page_name_title: str = "介面名稱"
    platform_edit_page_name_content: str = "請輸入介面名稱，僅用於應用程式內顯示，無實際作用"
    platform_edit_page_api_url: str = "請輸入介面網址 …"
    platform_edit_page_api_url_title: str = "介面網址"
    platform_edit_page_api_url_content: str = "請輸入介面網址，請注意辨別結尾是否需要新增 /v1"
    platform_edit_page_api_key: str = "請輸入介面金鑰 …"
    platform_edit_page_api_key_title: str = "介面金鑰"
    platform_edit_page_api_key_content: str = "請輸入介面金鑰，例如 sk-d0daba12345678fd8eb7b8d31c123456，填入多個金鑰可以輪詢使用，每行一個"
    platform_edit_page_thinking_title: str = "優先使用思考模式"
    platform_edit_page_thinking_content: str = "對於同時支援思考模式和普通模式的模型，優先使用思考模式"
    platform_edit_page_model: str = "請輸入模型名稱 …"
    platform_edit_page_model_title: str = "模型名稱"
    platform_edit_page_model_content: str = "目前使用的模型為 {MODEL}"
    platform_edit_page_model_edit: str = "手動輸入"
    platform_edit_page_model_sync: str = "線上取得"

    # 參數編輯
    args_edit_page_top_p_title: str = "top_p"
    args_edit_page_top_p_content: str = "請謹慎設定，錯誤的值可能導致結果異常或請求錯誤"
    args_edit_page_temperature_title: str = "temperature"
    args_edit_page_temperature_content: str = "請謹慎設定，錯誤的值可能導致結果異常或請求錯誤"
    args_edit_page_presence_penalty_title: str = "presence_penalty"
    args_edit_page_presence_penalty_content: str = "請謹慎設定，錯誤的值可能導致結果異常或請求錯誤"
    args_edit_page_frequency_penalty_title: str = "frequency_penalty"
    args_edit_page_frequency_penalty_content: str = "請謹慎設定，錯誤的值可能導致結果異常或請求錯誤"
    args_edit_page_document_link: str = "點擊查看文件"

    # 模型清單
    model_list_page_title: str = "可用的模型清單"
    model_list_page_content: str = "點擊選取要使用的模型"
    model_list_page_fail: str = "取得模型清單失敗，請檢查介面設定 …"

    # 專案設定
    project_page_source_language_title: str = "原文語言"
    project_page_source_language_content: str = "設定目前專案中輸入文字的語言"
    project_page_target_language_title: str = "譯文語言"
    project_page_target_language_content: str = "設定目前專案中輸出文字的語言"
    project_page_input_folder_title: str = "輸入資料夾"
    project_page_input_folder_content: str = "目前輸入資料夾為"
    project_page_output_folder_title: str = "輸出資料夾（不能與輸入資料夾相同）"
    project_page_output_folder_content: str = "目前輸出資料夾為"
    project_page_output_folder_open_on_finish_title: str = "任務完成時開啟輸出資料夾"
    project_page_output_folder_open_on_finish_content: str = "啟用此功能後，將在任務完成時自動開啟輸出資料夾"
    project_page_traditional_chinese_title: str = "使用繁體輸出中文"
    project_page_traditional_chinese_content: str = "啟用此功能後，在譯文語言設定為中文時，將使用繁體字形輸出中文文字"

    # 開始翻譯
    translation_page_status_idle: str = "無任務"
    translation_page_status_testing: str = "測試中"
    translation_page_status_translating: str = "翻譯中"
    translation_page_status_stopping: str = "停止中"
    translation_page_indeterminate_saving: str = "快取檔案儲存中 …"
    translation_page_indeterminate_stoping: str = "正在停止翻譯任務 …"
    translation_page_card_time: str = "累計時間"
    translation_page_card_remaining_time: str = "剩餘時間"
    translation_page_card_line: str = "翻譯行數"
    translation_page_card_remaining_line: str = "剩餘行數"
    translation_page_card_speed: str = "平均速度"
    translation_page_card_token: str = "累計消耗"
    translation_page_card_task: str = "即時任務數"
    translation_page_alert_pause: str = "停止的翻譯任務可以隨時繼續翻譯，是否確定停止任務 … ？"
    translation_page_continue: str = "繼續任務"
    translation_page_export: str = "匯出任務資料"
    translation_page_timer: str = "請設定延遲啟動前要等待的時間"

    # 基礎設定
    basic_settings_page_max_workers_title: str = "並行任務門檻值"
    basic_settings_page_max_workers_content: str = (
        "同時執行的任務數量的最大值"
        "<br>"
        "合理設定可以顯著加快任務的完成速度，請參考 API 平台的說明文件進行設定，0 = 自動"
        ""
        ""
    )
    basic_settings_page_rpm_threshold_title: str = "每分鐘任務數量門檻值"
    basic_settings_page_rpm_threshold_content: str = (
        "每分鐘執行的任務總數量的最大值，即 <font color='darkgoldenrod'><b>RPM</b></font> 門檻值"
        "<br>"
        "合理設定可以顯著加快任務的完成速度，請參考 API 平台的說明文件進行設定，0 = 自動"
        ""
        ""
    )
    basic_settings_page_token_threshold_title: str = "任務長度門檻值"
    basic_settings_page_token_threshold_content: str = "每個任務所包含的文字的最大 Token 數量"
    basic_settings_page_request_timeout_title: str = "逾時時間門檻值"
    basic_settings_page_request_timeout_content: str = (
        "發起請求時等待模型回覆的最長時間（秒），逾時仍未收到回覆，則會判斷為任務失敗"
        ""
        ""
    )
    basic_settings_page_max_round_title: str = "任務回合門檻值"
    basic_settings_page_max_round_content: str = "當完成一輪任務後，將在新的回合中對失敗的任務進行重試，直到全部完成或達到回合門檻值"

    # 專家設定
    expert_settings_page_preceding_lines_threshold: str = "參考上文行數門檻值"
    expert_settings_page_preceding_lines_threshold_desc: str = "每個翻譯任務最多可攜帶的參考上文的行數，預設 3 行"
    expert_settings_page_preceding_disable_on_local: str = "本地介面啟用參考上文"
    expert_settings_page_preceding_disable_on_local_desc: str = "本地模型效能較差，參考上文功能大部分時候是負面效果，預設停用"
    expert_settings_page_deduplication_in_bilingual: str = "雙語輸出檔案中對重複行去重複"
    expert_settings_page_deduplication_in_bilingual_desc: str = "在雙語輸出檔案中，原文與譯文一致時是否去重複，預設啟用"
    expert_settings_page_write_translated_name_fields_to_file: str = "將姓名字段譯文寫入輸出檔案"
    expert_settings_page_write_translated_name_fields_to_file_desc: str = (
        "部分 <font color='darkgoldenrod'><b>GalGame</b></font> 中，姓名字段資料與立繪、配音等資源檔案綁定，翻譯後會報錯，此時可以關閉該功能，預設啟用"
        "<br>"
        "支援格式："
        "<br>"
        "• RenPy 匯出遊戲文字（.rpy）"
        "<br>"
        "• VNTextPatch 或 SExtractor 匯出帶 name 欄位的遊戲文字（.json）"
        ""
        ""
    )
    expert_settings_page_result_checker_retry_count_threshold: str = "結果檢查 - 重試次數達到門檻值"
    expert_settings_page_result_checker_retry_count_threshold_desc: str = (
        "是否在結果檢查報告裡面輸出 <font color='darkgoldenrod'><b>重試次數達到門檻值</b></font> 的項目列表"
        "<br>"
        "• 在進行翻譯結果檢查時，如果重試達門檻值依然未通過檢查，就會取最後一次的結果"
        "<br>"
        "• 透過此功能，就可以逐一確認最後的取值實際上是否正確的"
    )

    # 品質類通用
    quality_import: str = "匯入"
    quality_import_toast: str = "資料已匯入 …"
    quality_export: str = "匯出"
    quality_export_toast: str = "資料已匯出到應用程式根目錄 …"
    quality_save: str = "儲存"
    quality_save_toast: str = "資料已儲存 …"
    quality_merge_duplication: str = "已合併重複資料 …"
    quality_preset: str = "預設"
    quality_reset: str = "重設"
    quality_reset_toast: str = "資料已重設 …"
    quality_reset_alert: str = "是否確認重設為預設資料 … ？"
    quality_select_file: str = "選取檔案"
    quality_select_file_type: str = "支援的資料格式 (*.json *.xlsx)"
    quality_delete_row: str = "刪除行"
    quality_switch_regex: str = "切換正規表示法模式"

    # 詞彙表
    glossary_page_head_title: str = "詞彙表"
    glossary_page_head_content: str = "透過在提示詞中建構詞彙表來引導模型翻譯，可實現統一翻譯、校正人稱屬性等功能"
    glossary_page_table_row_01: str = "原文"
    glossary_page_table_row_02: str = "譯文"
    glossary_page_table_row_03: str = "描述"
    glossary_page_kg: str = "一鍵製作工具"

    # 文字保護
    text_preserve_page_head_title: str = "自訂文字保護規則"
    text_preserve_page_head_content: str = (
        "對文字中不需要翻譯的程式碼片段、控制字元、樣式字元等文字進行保護，避免這些文字被錯誤的翻譯"
        "<br>"
        "<font color='darkgoldenrod'><b>預設停用</b></font>，啟用前請仔細閱讀 <font color='darkgoldenrod'><b>Wiki</b></font> 中的功能說明以確保充分理解使用方式"
        "<br>"
        "• 啟用 - 根據本頁中設定的 <font color='darkgoldenrod'><b>正規表示法規則</b></font> 比對對應的文字進行保護"
        "<br>"
        "• 停用 - 自動判斷文字格式與遊戲引擎，智慧選擇合適的保護規則，在大部分內容中都可以取得較好的效果"
    )
    text_preserve_page_table_row_01: str = "規則"
    text_preserve_page_table_row_02: str = "備註（僅作備忘，無實際作用）"

    # 翻譯前取代
    pre_translation_replacement_page_head_title: str = "翻譯前取代"
    pre_translation_replacement_page_head_content: str = (
        "在翻譯開始前，將原文中比對的部分取代為指定的文字，執行的順序為由上到下依序取代"
        "<br>"
        "對於 <font color='darkgoldenrod'><b>RPGMaker MV/MZ</b></font> 引擎的遊戲："
        "<br>"
        "• 匯入遊戲目錄的 <font color='darkgoldenrod'><b>data</b></font> 或 <font color='darkgoldenrod'><b>www\\data</b></font> 資料夾內的 <font color='darkgoldenrod'><b>actors.json</b></font> 檔案可以顯著提升翻譯品質"
        "<br>"
        "• 遊戲中包含自訂姓名功能時需要進行特殊處理，請點擊右下角按鈕跳轉並仔細閱讀 <font color='darkgoldenrod'><b>Wiki</b></font> 相關頁面中的說明"
    )
    pre_translation_replacement_page_table_row_01: str = "原文"
    pre_translation_replacement_page_table_row_02: str = "取代"
    pre_translation_replacement_page_table_row_03: str = "正規表示法"

    # 翻譯後取代
    post_translation_replacement_page_head_title: str = "翻譯後取代"
    post_translation_replacement_page_head_content: str = "在翻譯完成後，將譯文中比對的部分取代為指定的文字，執行的順序為由上到下依序取代"
    post_translation_replacement_page_table_row_01: str = "原文"
    post_translation_replacement_page_table_row_02: str = "取代"
    post_translation_replacement_page_table_row_03: str = "正規表示法"

    # 自訂提示詞 - 中文
    custom_prompt_zh_page_head: str = "自訂中文提示詞（不支援 SakuraLLM 模型）"
    custom_prompt_zh_page_head_desc: str = (
        "透過自訂提示詞追加故事設定、行文風格等額外翻譯要求"
        "<br>"
        "注意：前綴與後綴部分固定不可修改，只有 <font color='darkgoldenrod'><b>譯文語言設定為中文時</b></font> 才會使用本頁中的自訂提示詞"
        ""
        ""
    )

    # 自訂提示詞 - 英文
    custom_prompt_en_page_head: str = "自訂英文提示詞（不支援 SakuraLLM 模型）"
    custom_prompt_en_page_head_desc: str = (
        "透過自訂提示詞追加故事設定、行文風格等額外翻譯要求"
        "<br>"
        "注意：前綴與後綴部分固定不可修改，只有 <font color='darkgoldenrod'><b>譯文語言設定為非中文時</b></font> 才會使用本頁中的自訂提示詞"
        ""
        ""
    )

    # 實驗室
    laboratory_page_mtool_optimizer_enable: str = "MTool 最佳化工具"
    laboratory_page_mtool_optimizer_enable_desc: str = (
        "在對 MTool 文字進行翻譯時，至多可減少 40% 的 翻譯時間 與 Token 消耗"
        "<br>"
        "可能導致 <font color='darkgoldenrod'><b>原文殘留</b></font> 或 <font color='darkgoldenrod'><b>語句不連貫</b></font> 等問題，請 <font color='darkgoldenrod'><b>自行判斷</b></font> 是否啟用，並且只應在 <font color='darkgoldenrod'><b>翻譯 MTool 文字時</b></font> 啟用"
        ""
        ""
        ""
        ""
        ""
        ""
    )
    laboratory_page_auto_glossary_enable: str = "自動補全詞彙表（不支援 SakuraLLM 模型）"
    laboratory_page_auto_glossary_enable_desc: str = (
        "翻譯的同時嘗試自動補全詞彙表中缺失的專有名詞項目，只有在 <font color='darkgoldenrod'><b>啟用詞彙表功能</b></font> 時才生效"
        "<br>"
        "此功能設計目的僅為查漏補缺，並不能取代 <font color='darkgoldenrod'><b>KeywordGacha</b></font>，取得的補充詞彙將直接 <font color='darkgoldenrod'><b>寫入詞彙表</b></font>"
        "<br>"
        "可能會產生 <font color='darkgoldenrod'><b>不正確或不合適的詞彙項目</b></font>，請 <font color='darkgoldenrod'><b>自行判斷</b></font> 是否啟用，建議僅在 DeepSeek V3/R1 等級的強力模型使用此功能"
        ""
        ""
        ""
        ""
    )

    # 百寶箱
    tool_box_page_batch_correction: str = "批次修正"
    tool_box_page_batch_correction_desc: str = "根據翻譯完成時產生的結果檢查檔案中的資料，對可能存在的翻譯錯誤進行批次修正，實現快速修正譯文結果的目的"
    tool_box_page_re_translation: str = "部分重翻"
    tool_box_page_re_translation_desc: str = "根據設定的篩選條件，重新對已完成的翻譯文字中的部分內容進行翻譯，主要用於內容的更新或錯誤的修正"
    tool_box_page_name_field_extraction: str = "姓名字段擷取"
    tool_box_page_name_field_extraction_desc: str = (
        "擷取 <font color='darkgoldenrod'><b>RenPy</b></font> 和 <font color='darkgoldenrod'><b>GalGame</b></font> 遊戲文字中的角色姓名字段資料，"
        "自動產生對應的詞彙表資料，方便後續進行翻譯"
    )

    # 百寶箱 - 批次修正
    batch_correction_page: str = "批次修正"
    batch_correction_page_desc: str = (
        "根據翻譯完成時產生的結果檢查檔案中的資料，對可能存在的翻譯錯誤進行批次修正，然後產生修正後的譯文檔案"
        "<br>"
        "工作流程："
        "<br>"
        "• 從 <font color='darkgoldenrod'><b>輸入資料夾</b></font> 的翻譯結果檢查檔案中擷取可能需要修正的資料"
        "<br>"
        "• 檢查擷取出的資料，並根據實際情況對需要修正的項目進行修正"
        "<br>"
        "• 將修正後的資料注入 <font color='darkgoldenrod'><b>輸入資料夾</b></font> 中的譯文檔案，然後在 <font color='darkgoldenrod'><b>輸出資料夾</b></font> 產生修正後的譯文檔案"
    )
    batch_correction_page_step_01: str = "第一步 - 產生修正資料"
    batch_correction_page_step_01_desc: str = (
        "從結果檢查檔案中擷取可能包含翻譯錯誤的資料"
        "<br>"
        f"然後自動在 <font color='darkgoldenrod'><b>輸出資料夾</b></font> 內產生用於編輯的資料檔案 <font color='darkgoldenrod'><b>{path_result_batch_correction}</b></font>"
    )
    batch_correction_page_step_02: str = "第二步 - 注入修正資料"
    batch_correction_page_step_02_desc: str = (
        "檢查資料檔案中的內容，確認無誤後 <font color='darkgoldenrod'><b>關閉</b></font> 檔案，開始注入"
        "<br>"
        "請注意："
        "<br>"
        "• 除 <font color='darkgoldenrod'><b>修正欄</b></font> 以外，不要修改資料檔案內的其他資料"
        "<br>"
        "• 部分格式的譯文檔名中會包含類似 <font color='darkgoldenrod'><b>.zh</b></font> 的語言後綴，在注入前請從檔名中移除語言後綴以正確比對資料"
    )
    batch_correction_page_title_01: str = "檔名"
    batch_correction_page_title_02: str = "錯誤類型"
    batch_correction_page_title_03: str = "原文（勿修改此欄）"
    batch_correction_page_title_04: str = "譯文（勿修改此欄）"
    batch_correction_page_title_05: str = "修正（請修改此欄）"

    # 百寶箱 - 部分重翻
    re_translation_page: str = "部分重翻"
    re_translation_page_desc: str = (
        "將根據設定的篩選條件對 <font color='darkgoldenrod'><b>輸入資料夾</b></font> 中的文字進行篩選，然後對符合條件的文字進行重翻"
        "<br>"
        "工作流程："
        "<br>"
        "• 分別從 <font color='darkgoldenrod'><b>輸入資料夾</b></font> 的 <font color='darkgoldenrod'><b>src</b></font> 與 <font color='darkgoldenrod'><b>dst</b></font> 子目錄中讀取原文與譯文"
        "<br>"
        "• 原文檔案和譯文檔案的檔名和檔案內容必須嚴格一一對應"
        "<br>"
        "• 根據本頁中的設定篩選出需要重翻的文字，按正常流程進行翻譯，翻譯完成後輸出更新後的譯文檔案"
    )
    re_translation_page_white_list: str = "關鍵字 - 白名單"
    re_translation_page_white_list_desc: str = (
        "包含這些關鍵字的文字將被重新翻譯，可以填入多個關鍵字，每行一個，只需要命中其中之一即判斷為需要重翻的文字"
        ""
        ""
    )
    re_translation_page_alert_not_equal: str = "原文与译文的行数不匹配 …"

    # 百寶箱 - 姓名字段擷取
    name_field_extraction_page: str = "姓名字段擷取"
    name_field_extraction_page_desc: str = (
        "將從 <font color='darkgoldenrod'><b>輸入資料夾</b></font> 中所有符合條件的檔案中擷取角色姓名字段，自動產生對應的詞彙表資料"
        "<br>"
        "請注意：此功能 <font color='darkgoldenrod'><b>不能擷取正文內的詞彙</b></font>，不能取代 <font color='darkgoldenrod'><b>KeywordGacha</b></font> 工具"
        "<br>"
        "支援格式："
        "<br>"
        "• RenPy 匯出遊戲文字（.rpy）"
        "<br>"
        "• VNTextPatch 或 SExtractor 匯出帶 name 欄位的遊戲文字（.json）"
    )
    name_field_extraction_page_step_01: str = "第一步 - 擷取資料"
    name_field_extraction_page_step_01_desc: str = (
        "擷取姓名字段及其相關的上下文，傳送至翻譯器進行翻譯"
        "<br>"
        f"翻譯完成後，將在 <font color='darkgoldenrod'><b>輸出資料夾</b></font> 內產生 <font color='darkgoldenrod'><b>{path_result_name_field_extraction}</b></font> 檔案"
    )
    name_field_extraction_page_step_02: str = "第二步 - 產生詞彙表"
    name_field_extraction_page_step_02_desc: str = (
        f"將從 <font color='darkgoldenrod'><b>輸出資料夾</b></font> 內的 <font color='darkgoldenrod'><b>{path_result_name_field_extraction}</b></font> 檔案中擷取翻譯後的資料"
        "<br>"
        "然後產生對應的詞彙表資料，請注意檢查產生的詞彙表資料是否正確"
    )